### ISSUE TITLE
Add documentation to addresses pattern about the use of the footer with copyright

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1959] opened 2022-02-08 13:58 UTC
Add documentation to the Addresses pattern about the use of the footer variant with 'OS address data terms and conditions' when using this pattern.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/412#issuecomment-713477098_

Linked to #1112

**Comment by jrbarnes9** [comment] 2022-02-11 11:52
Dupe of #1112

**Closed by jrbarnes9** 2022-02-11 11:52 UTC
Labels: Documentation
