### ISSUE TITLE
Add guidance around using unit prefix/suffixes to ensure uncommon unit abbreviations are spelled out in the question or input label

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1983] opened 2022-02-09 15:59 UTC
We should add guidance around using unit prefix/suffixes to ensure uncommon unit abbreviations are spelled out in the question or input label

Example of guidance from GDS: 
> Prefixes and suffixes are useful when there’s a commonly understood symbol or abbreviation for the type of information you’re asking for. Do not rely on prefixes or suffixes alone, because screen readers will not read them out.

> If you need a specific type of information, say so in the input label or hint text as well. For example, put ‘Cost, in pounds’ in the input label and use the ‘£’ symbol in the prefix.

Also, update all the examples to ensure the unit is spelt out in the label.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/279#discussioncomment-1042326_

Linked to #1604

**Comment by jrbarnes9** [comment] 2022-02-11 12:11
Dupe of #1604

**Closed by jrbarnes9** 2022-02-11 12:11 UTC
Labels: Documentation
