### ISSUE TITLE
duplicate of 1876? [Spike] Can we reduce the amount of examples/variants by using config controls?

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1938] opened 2022-02-04 15:40 UTC
Would be really useful if we could reduce the number of examples users have to trawl through to find the one appropriate for their needs.

A good example: https://material.io/components/text-fields

**Comment by jrbarnes9** [comment] 2022-02-11 11:43
Dupe of #1876

**Closed by jrbarnes9** 2022-02-11 11:43 UTC
Labels: Enhancement, Documentation
