### ISSUE TITLE
[Bug]: Header width tied to content width

### ISSUE THREAD

**Issue by BenLatham** [ONSdigital/design-system#3357] opened 2024-09-17 11:36 UTC
### Describe the bug

In the design system layout, the header `wide` and `fullWidth` parameters are determined by the corresponding pageConfig parameters, rather than by `pageConfig.header` parameters.

This results in a situation where the width of the header is coupled to the width of the page contents.

In some cases an application/site may have some pages that need to use a `fullWidth` or `wide` layout while other pages use a standard layout. When users switch between these pages they expect the header to remain unchanged, with for example, nav links remaining in the same position on the screen. Instead the changes in width of the header box cause the contents of the header to appear to move when switching from wide to standard pages.

### Expected behaviour / outcome

- When switching from a page with wide content to narrow content, the layout of the header is unchanged.
- The width of the content can be configured independently from the width of the header.

### List the steps necessary to reproduce the bug

- Create two pages using the same header using the design system layout
-  Configure one page with `fullWidth:True` and one without.
- Switch between the pages.
- The header can be observed shifting leftwards when moving to the fullWidth page, as it no longer sits in a fixed width container.

### Additional context

Where the `onsHeader` macro is called in the layout template, the lines:
```                             
    "wide": pageConfig.wide,
    "fullWidth": pageConfig.fullWidth,
 ```
Could instead be:
 ```                             
    "wide": pageConfig.header.wide | default(pageConfig.wide),
    "fullWidth": pageConfig.header.fullWidth  | default(pageConfig.fullWidth),
 ```
 Allowing the header to be optionally set to a different width than the page contents.

### What version of the ONS Design System are you using?

70.0.0

### What device(s) are you using?

Desktop

### What operating system(s) are you using?

Windows, macOS

### What browser(s) are you using?

Firefox, Chrome, Microsoft Edge

**Comment by adi-unni** [comment] 2024-10-29 15:38
Ive linked a PR with some changes on a branch that implements the changes requested and some test examples (albeit with improper names as they were just tests). They can be found in _src/foundations/page-template/example-custom-test-two.njk_ and _src/foundations/page-template/example-custom-test.njk_ and they talk about the request. In this circumstance, this is not a bug of the original feature, rather an enhancement and one that I'm not sure we want to properly implement.

We would have to look deeper into the use case for this request and whether it aligns with the rest of the examples:

It allows for situations like this:

![Image](https://github.com/user-attachments/assets/3cd574a1-cbf3-4904-a5fc-96eed29fa099)

where the header and the footer can be set independently to _full-width_ and _wide_

**Comment by rmccar** [comment] 2024-10-31 20:02
Blocked waiting on discussion with designers

**Comment by rmccar** [comment] 2024-11-07 15:56
Hi @BenLatham can you give us some more information on why you need this? Having discussed this we think that the width of the content should match the width of the header and footer and this is therefore not a bug and is more a feature of the DS. In the case where you need full width content, we think the best experience for the users would be to either have all the pages full width rather than switching between the two or better still would be to display content that you need full width for in a different way so that the content fits the standard layout. However we don't have all the information on your use case.

**Comment by BenLatham** [comment] 2024-11-12 10:20
@rmccar on our site we have several pages where there are quite large data tables (since it's an internal site used by RAP and BDOD the need to compare data quickly outweighed the need for simplicity). These pages need to be full width to avoid the need for horizontal scrolling. On most other pages within the site, however the standard width presentation is preferable, since it provides a cleaner view (such as user journeys where they select the survey and period to display, or search pages). All these pages have a common header and footer. When switching from the wide to the standard pages (and vice-versa) the nav links, page header and other header elements appear to jump from one location to another on the screen, giving a jarring user experience.

**Comment by rmccar** [comment] 2024-11-19 14:52
After having discussions with Ben we have decided that this isn't something that we can support on the DS so we are going to have to close this issue

**Closed by rmccar** 2024-11-19 14:52 UTC
Labels: Bug, Community backlog, High priority, Upcoming
