### ISSUE TITLE
Use of `autocomplete` needs more work and guidance regarding its use in survey questions where the integrity of the data could suffer from pre-population

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1939] opened 2022-02-04 15:40 UTC
Use of `autocomplete` needs more work and guidance regarding its use in survey questions where the integrity of the data could suffer from pre-population

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/163#issuecomment-470123980_

**Comment by jrbarnes9** [comment] 2022-02-11 11:45
Dupe of #275

**Closed by jrbarnes9** 2022-02-11 11:45 UTC
Labels: Enhancement, Documentation
