### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#233] opened 2019-02-22 14:39 UTC
Use this issue to discuss [Typography](https://ons-design-system.netlify.com/styles/typography) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment] 2019-05-15 08:20
Currently the default font sizes for headings are always one step larger than we actually use by default, meaning everywhere we use a heading we have to use a font size utility class. We should change the default font sizes for headings to what we set them to with utility classes, and then remove utility classes from the headings.

**Comment by jrbarnes9** [comment] 2019-05-15 18:15
H4 headings are the same at the base font style, so it's impossible to differentiate between a paragraph and an h4 heading.

**Comment by bameyrick** [comment] 2019-06-06 14:36
The spacing between numbers are off. The font files need to be regenerated with "Proportional Figures" turned on.

Proportional Figures off:
![Screenshot 2019-06-06 at 15 34 48](https://user-images.githubusercontent.com/8447446/59041538-b40d5c80-8870-11e9-8b1f-11429925308a.png)

Proportional Figures on:
![Screenshot 2019-06-06 at 15 34 56](https://user-images.githubusercontent.com/8447446/59041540-b40d5c80-8870-11e9-9fac-039857b9cad8.png)

**Comment by jeremygillies** [comment] 2019-10-16 09:34
The .ttf format of Open Sans can implement `font-variant-numeric: tabular-nums;` which activates the set of figures where numbers are all of the same size, allowing them to be easily aligned in tables. It's required according to the ONS Styleguide : https://style.ons.gov.uk/category/data-visualisation/tables/#fonts

OpenSans (.woff) 
![image](https://user-images.githubusercontent.com/1080383/66906436-9e1e5e00-efff-11e9-8a09-ff8d7a4507ec.png)

Open Sans (.ttf)
![image](https://user-images.githubusercontent.com/1080383/66906477-b2faf180-efff-11e9-84f5-62289c173eee.png)

Looks like our font doesn't contain the monospaced `1` glyph

**Comment by jrbarnes9** [comment] 2020-06-10 08:01
Add external link guidance including warning users (with text) when an link will open in a new window (web chat example)

**Comment by jrbarnes9** [comment] 2020-06-26 10:08
Define how postal address should be marked up/displayed

**Comment by jrbarnes9** [comment] 2020-06-29 08:44
We shouldn't use colour as the only indicator of hover states on links, accordions and buttons etc 

https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html

**Comment by trevorsaint** [comment] 2020-07-13 13:32
I’ve spotted a bug with the bare list that needs fixing. 

If we need the full width to be clickable, there are tricks to make this happen without the full width focus style. This may have been done for mobile benefits to allow a greater touch area.

![image](https://user-images.githubusercontent.com/4989027/87309891-1d9c7780-c515-11ea-935b-8fcb13d7fd7b.png)

**Comment by trevorsaint** [comment] 2020-07-23 16:15
### Typography is rendering differently in Firefox than it is in Chrome

**We have** 
`-webkit-font-smoothing: antialiased;` 

**Missing** 
`-moz-osx-font-smoothing: grayscale;`

Adding this should fix the issue, ensuring typography consistency.

**Chrome**
![image](https://user-images.githubusercontent.com/4989027/88310178-42f46700-cd07-11ea-844f-4c3b3105e30b.png)

**Firefox rendering thicker**
![image](https://user-images.githubusercontent.com/4989027/88310142-37a13b80-cd07-11ea-8fbd-108eb608cfb2.png)

**Comment by Paul-Joel** [comment] 2020-09-22 12:06
The prefix option in lists no longer works after #892 (released in v22.0.0)
The issue seems to be that 'prefixText' has been introduced to replace 'prefix', but 'prefix' still exists, and the code checks for 'prefix', then writes out 'prefixText'
The prefix setting is in the Census help pages, and is now broken.
It should also have been marked as a breaking change, as Craft was using 'prefix', which no longer displays the value.
There is an earlier possible issue as well that if a prefix is specified, you additionally have to manually declare 'list--bare' to stop it writing out both the automatic bullets and the prefix - this used to be added automatically

**Comment by jrbarnes9** [comment] 2020-09-23 10:52
Dashed list example missing from list styles

**Comment by trevorsaint** [comment] 2020-09-29 13:35
A property added to `.list__item` is causing list item content to not break when expected.

`white-space: nowrap;` is going to prevent a break in typography. This may have been added to fix other functionality but can’t be added at the global level.

**Current behaviour**
![image](https://user-images.githubusercontent.com/4989027/94565253-e1013200-0260-11eb-84e7-5c4020fec44c.png)

**Expected behaviour**
![image](https://user-images.githubusercontent.com/4989027/94565298-f1b1a800-0260-11eb-9a85-e612fcc04e9f.png)

**Comment by trevorsaint** [comment] 2020-10-05 09:46
When applying icon modifiers, for example: `svg-icon--m, l, xl` and so on we seem to be adding a margin top. 

When used in lists with icons we have a problem with alignment due to a margin top being applied.

**A standard list with icons looks like this:**

<img width="295" alt="Screenshot 2020-10-05 at 10 29 30" src="https://user-images.githubusercontent.com/4989027/95063025-b3e7d000-06f5-11eb-99a1-a6bf6545c790.png">

Applying a size modifier you get this:

<img width="303" alt="Screenshot 2020-10-05 at 10 31 45" src="https://user-images.githubusercontent.com/4989027/95063223-fdd0b600-06f5-11eb-88f5-197cafa31c3b.png">

I think to keep flexibility with icon scale we should remove the margin attribute.

### This has a knock on effect with using icons in panels
Alignment issues exist which is why margin top was added initially.

It may be a better idea to add utility classes for finer alignment tweaks, rather than adding it directly to the icon scale modifier.

**Comment by trevorsaint** [comment] 2020-10-13 09:48
I need the ability to define `rel` attributes for the list links.

For example, social links may want something along the lines of `rel="noreferrer external"`.
<img width="384" alt="Screenshot 2020-10-13 at 10 48 06" src="https://user-images.githubusercontent.com/4989027/95845045-99d76e80-0d41-11eb-9eb6-9ffdd17dac79.png">

**Comment by trevorsaint** [comment] 2020-10-14 10:56
List items not clearing correctly.

Rather than using floats for the icons we should consider using flexbox. If this is not possible due to browser compatibility limitations, we will need to add a clear fix for the list items.

**See the issue below**
<img width="536" alt="Screenshot 2020-10-14 at 11 52 13" src="https://user-images.githubusercontent.com/4989027/95979753-0884fc80-0e14-11eb-97be-8d08c153f2cb.png">

**Comment by trevorsaint** [comment] 2020-10-19 08:49
Inline lists don’t play nicely with icons.

<img width="601" alt="Screenshot 2020-10-19 at 09 43 00" src="https://user-images.githubusercontent.com/4989027/96422167-9a637f80-11ef-11eb-9e9c-0d9a8164ed77.png">

We seem to be specifying `.svg-icon` size specifically for use within inline lists. We don’t need this. It is going to override icon scale as you can see in the example. applying a modifier in the case won’t have an effect due to specificity.

<img width="346" alt="Screenshot 2020-10-19 at 09 44 27" src="https://user-images.githubusercontent.com/4989027/96422321-c67f0080-11ef-11eb-9105-813d1b9da3fe.png">

**Removing the attribute** works just fine as the example below shows. The gap however is far too big between inline list items.
<img width="592" alt="Screenshot 2020-10-19 at 09 44 42" src="https://user-images.githubusercontent.com/4989027/96422667-38574a00-11f0-11eb-895b-2538a061a89e.png">

**Comment by jrbarnes9** [comment] 2020-10-30 15:21
Need a way to adjust quote component to reduce font size/style to allow for longer block quotes e.g. a quote from a director within a press release

**Comment by jrbarnes9** [comment] 2020-11-17 10:51
Add the ability to also set suffixIcon as well as `prefixIcon`

**Closed** 2020-12-09 12:01 UTC
Labels: Design System forum, Style
