### ISSUE TITLE
The link when setting up the ONS-prototype-kit is wrong

### ISSUE THREAD

**Issue by Majsol** [ONSdigital/design-system#2880] opened 2023-11-01 09:52 UTC
The first link in the overview is not leading to the right page: https://service-manual.ons.gov.uk/design-system/guidance/ons-prototype-kit 
...it is leading to this page https://github.com/ONSdigital/prototype-kit 
...but I think it needs to lead to this page instead: https://github.com/ONSdigital/prototype-kit-template

**Comment by yatesn** [comment] 2023-11-07 16:43
Needs investigating

**Comment by JNATION85** [comment] 2023-12-07 10:29
Need to review documentation and vision for the prototype kit

**Comment by alessioventuriniAND** [comment] 2023-12-13 14:22
@OscarJackson Could we take you through the process of setting up a prototype kit project so that you could help us improve the documentation of this page? : https://service-manual.ons.gov.uk/design-system/guidance/ons-prototype-kit

**Comment by daniellecorke** [comment] 2024-02-15 10:12
Content design required - raise with Vicki C.

**Comment by daniellecorke** [comment] 2024-03-28 14:46
Alessio to speak to Angharad.

**Comment by alessioventuriniAND** [comment] 2024-04-03 12:53
I have checked this page and I can confirm that the link is not wrong. Looking at the way the content has been setup it looks like the intention is to take users through the README file of the prototype-kit repo which will then explain the users how to create a new prototype-kit project using the prototype-kit-template repo. I have followed the steps in the docs and I was able to create a new template project and run it locally. 

I will need to confirm with Dina that she is happy with my findings and potentially open a different ticket if the content of the page needs improving to streamline the user experience when creating a new prototype.

**Comment by daniellecorke** [comment] 2024-05-22 12:26
@alessioventuriniAND do you think this work is now being covered by [#41](https://github.com/ONSdigital/prototype-kit/issues/41) and [#45](https://github.com/ONSdigital/prototype-kit/issues/45)?

**Comment by alessioventuriniAND** [comment] 2024-05-22 13:19
I do :)

**Comment by daniellecorke** [comment] 2024-05-22 13:47
Closing this ticket as investigations were completed and we now have new tickets in progress to look into the Prototype kit documentation as a whole.

**Closed by daniellecorke** 2024-05-22 13:47 UTC
Labels: Refined(Tech)
