### ISSUE TITLE
Save and sign out example button not using the 'exit' icon in the footer

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1976] opened 2022-02-09 15:38 UTC
Save and sign out example button not using the 'exit' icon in the footer

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1476#discussioncomment-1626910_

Linked to #1765

**Comment by jrbarnes9** [comment] 2022-02-11 11:32
Dupe of #1765

**Closed by jrbarnes9** 2022-02-11 11:32 UTC
Labels: Documentation
