### ISSUE TITLE
Runner error panel spacing issue

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2092] opened 2022-03-28 10:34 UTC
![image](https://user-images.githubusercontent.com/42928680/160380288-8851becd-8d95-4756-9f7f-98b5db1cb015.png)

**Comment by jrbarnes9** [comment] 2022-03-29 09:21
@rmccar This looks like a dupe of #1896?

**Comment by rmccar** [comment] 2022-03-29 09:26
> @rmccar This looks like a dupe of #1896?

Yeah looks like it, do you want me to close it and link my PR to the other one?

**Closed** 2022-04-06 08:14 UTC
