### ISSUE TITLE
Panel autofocus accessibility issue

### ISSUE THREAD

**Issue by pricem14pc** [ONSdigital/design-system#3447] opened 2024-12-04 08:51 UTC
### Describe the accessibility issue

DAC testing of SDC Response Operations raised the following issue;
> Focus order 3
The focus order of the page was illogical.

>WCAG Reference
2.4.3 Focus Order (Level A)
https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html | https://www.w3.org/WAI/WCAG21/quickref/#focus-order

Although DAC recommend using the ONS design system to resolve this in our use case, we are using the DS and the underlying issue is the conditional inclusion of the autofocus attribute in the pannel
```
{% if not isDesignSystemExample %}autofocus="autofocus"{% endif %}
```
https://github.com/ONSdigital/design-system/blob/main/src/components/panel/_macro.njk#L32

### Expected behaviour / outcome

panel shouldn't include autofocus attribute, or make it configurable per useage.

### List the steps necessary to reproduce the bug

see description.

### What version of the ONS Design System are you using?

70.0.1 (in progress upgrading to 72.X)

### What device(s) are you using?

Desktop

### What operating system(s) are you using?

macOS

### What browser(s) are you using?

Chrome

**Comment by MagdalenaLarge** [comment] 2024-12-04 10:50
@pricem14pc Hi, thank you for highlighting this issue to us. We will look into it and let you know once the issue is resolved.

**Comment by rmccar** [comment] 2024-12-20 10:13
On investigation to solve some updates were needed to the way the panel was being used in the service so closing this one for now

**Closed by rmccar** 2024-12-20 10:13 UTC
Labels: Accessibility, Community backlog, Upcoming
