### ISSUE TITLE
[Bug]: section_navigation highlighting

### ISSUE THREAD

**Issue by Paul-Joel** [ONSdigital/design-system#2037] opened 2022-03-09 12:37 UTC
### What happened?

Using the section_navigation macro there is an issue where multiple nav options get highlighted when specifying a currentPath where one path is an extended url of another path

### What was the expected outcome?

Only the current page nav option gets highlighted

### How is this problem impacting your service?

Minor annoyance - I have got around it by changing my urls slightly

### What list of steps can be followed to reproduce the bug or issue?

Use the section_navigation macro. 

Set option 1 url = response/historic-responses
Set option 2 url = response/historic-responses-adjusted
Set currentPath to option 2 url

When on option 1 page the current tab is highlighted as option 1, but when on option 2 page options 1 and 2 are highlighted

I think this is because the test uses an 'in' and as option 1 is in option 2, both get highlighted

### What version of the ONS Design System are you using?

45.2.2

### What devices are you seeing the problem on?

- [ ] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by yatesn** [comment] 2022-08-19 09:05
Duplicate of #2206

**Closed by yatesn** 2022-08-19 09:05 UTC
Labels: Bug
